### ISSUE TITLE
Fish shell support. 

### ISSUE THREAD

**Issue by ChristianBagley** [qw3rtman/p#13]
Currently, p is not working in Fish shell - at least with full functionality. You can use p in Fish shell to install and then use 'p 2.7.10' to switch the version. However, the interactive selection and detection of config.fish (as opposed to zshrc or bashrc) is not implemented. I've forked to try and work on the issue, but would welcome help from those more experienced with Fish.

**Comment by qw3rtman** [comment]
This isn't at the top of my list for `p` right now.

Writing portable Shell scripts is a painful process and one that doesn't bring much benefit. Most systems have Bash pre-installed and those that don't can install Bash easily.

For now, I'll list Bash as a dependency. If you can add Fish shell support, feel free to send in a PR.
