### ISSUE TITLE
Possible Name Change

### ISSUE THREAD

**Issue by qw3rtman** [qw3rtman/p#15]
Was toying with the idea of a name change in order to prevent any conflicts and make the purpose of the script easily understood from the name.

How does `pvm` (for Python Version Manager) sound?

**Comment by srujayk** [comment]
I would normally support a change as a name with a single letter may cause problems, but I recently saw p on multiple places including the [Environment Management section on awesome-python](https://github.com/vinta/awesome-python#environment-management), and it may cause confusion if the name were to change.
