### ISSUE TITLE
just can't alter python version to 2.7.10

### ISSUE THREAD

**Issue by VoyageCN** [qw3rtman/p#25]
I use p to install 2.7.10 version but can't alter to it
the terminal info always be that 
activate : 2.7.10

  Success: Now using Python 2.7.11!

I use mac and the 2.7.11 is installed at /usr/local/Frameworks/Python.frameworks/

**Comment by qw3rtman** [comment]
After installing a Python version with `p`, it runs `python --version` to determine the current activated version. This sounds like it's an issue with your `$PATH`. You may need to prefix your `$PATH` environment variable with `/usr/local/p/versions/python` with

```sh
PATH=/usr/local/p/versions/python:$PATH
```

If you don't want to keep entering this command, you can add this line to your shell's startup script (such as `~/.bashrc` or `~/.zshrc`):

```sh
export PATH=/usr/local/p/versions/python:$PATH
```

Hope this works. Let me know if it fixes your issue!

**Comment by VoyageCN** [comment]
I have resolve the problem , thank you all the same
