### ISSUE TITLE
Installed Python

### ISSUE THREAD

**Issue by wildtron** [qw3rtman/p#4]
I have Python2 and Python3 installed on my system using package management. Is there a way for `p` to have something like `p system` to use system installed version?

**Comment by qw3rtman** [comment]
`p default` switches to the Python version that was installed prior to using `p`; it essentially temporarily disables any Python version installed/activated by `p`.

Let me know if this is what you're looking for.

**Comment by shakna-israel** [comment]
@qw3rtman, it may be related, p utterly failed to find the system Python on my Raspberry Pi with the latest Raspbian installed.

**Comment by qw3rtman** [comment]
@shakna-israel, with `p default`? Could you make another issue for that?
